# Mozilla User Preferences

/* Do not edit this file.
 *
 * If you make changes to this file while the application is running,
 * the changes will be overwritten when the application exits.
 *
 * To make a manual change to preferences, you can visit the URL about:config
 * For more information, see http://www.mozilla.org/unix/customizing.html#prefs
 */

user_pref("accessibility.tabfocus", 7);
user_pref("browser.cache.disk.capacity", 512000);
user_pref("browser.download.manager.closeWhenDone", true);
user_pref("browser.download.manager.openDownloadedFiles", true);
user_pref("browser.link.open_newwindow", 3);
user_pref("browser.reuse_window", 1);
user_pref("browser.startup.homepage", "http://caminobrowser.org/start/");
user_pref("browser.startup.page", 0);
user_pref("browser.urlbar.autoFill", true);
user_pref("camino.check_default_browser", false);
user_pref("camino.enable_ad_blocking", true);
user_pref("camino.last_feed_prelaunch_version", "2110.08.06");
user_pref("camino.prefs_version", 3);
user_pref("camino.warn_when_closing", false);
user_pref("config.trim_on_minimize", true);
user_pref("general.useragent.locale", "en");
user_pref("image.animation_mode", "once");
user_pref("intl.accept_languages", "en-US,en,hi,ja,fr,de,es,it,pt,pt-PT");
user_pref("intl.charset.detector", "");
user_pref("keyword.enabled", true);
user_pref("network.cookie.prefsMigrated", true);
user_pref("network.dns.disableIPv6", true);
user_pref("network.dnsCacheEntries", 10485670);
user_pref("network.dnsCacheExpiration", 172800);
user_pref("network.http.max-connections", 60);
user_pref("network.http.max-connections-per-server", 30);
user_pref("network.http.max-persistent-connections-per-proxy", 20);
user_pref("network.http.max-persistent-connections-per-server", 20);
user_pref("network.http.pipelining", true);
user_pref("network.http.pipelining.maxrequests", 10);
user_pref("network.http.pipelining.ssl", true);
user_pref("network.http.proxy.pipelining", true);
user_pref("network.proxy.http", "localhost");
user_pref("network.proxy.http_port", 8123);
user_pref("network.proxy.ssl", "localhost");
user_pref("network.proxy.ssl_port", 8123);
user_pref("network.proxy.type", 1);
user_pref("nglayout.initialPaint.delay", 0);
user_pref("content.interrupt.parsing", true);
user_pref("content.max.tokenizing.time", 2250000);
user_pref("content.notify.backoffcount", 5);
user_pref("content.notify.interval", 750000);
user_pref("content.notify.ontimer", true);
user_pref("content.switch.threshold", 750000);
user_pref("security.enable_java", true);
user_pref("urlclassifier.keyupdatetime.https://sb-ssl.google.com/safebrowsing/newkey", 1283693511);

